### ISSUE TITLE
Open recent workspace is not keyboard friendly

### ISSUE THREAD

**Issue by jcpetkovich** [sbauer322/workspace-nav#5]
Workspace-nav solves part of the problem of keyboard only usage, but open recent workspace still leaves one fumbling for the mouse sadly.

Is there an easy way to fix this?

**Comment by sbauer322** [comment]
I plan to add a command to do so in an upcoming release... Until then you can add the following to your user keymap, where "pmeta-j" is the keybinding of your choosing:

```
[:editor "pmeta-j" :lt.plugins.workspace-nav/focus]
```
