### ISSUE TITLE
0.0.6 missing from lighttable plugin manager

### ISSUE THREAD

**Issue by jcpetkovich** [sbauer322/workspace-nav#6]
The newest version was tagged two months ago, but doesn't appear in the list of plugins in LightTable.

**Comment by Robsteranium** [comment]
I've created a PR with the updated plugin.edn https://github.com/LightTable/plugin-metadata/pull/22

**Comment by sbauer322** [comment]
0.0.6 is in the Light Table plugin manager now. Thanks!
