### ISSUE TITLE
Focus in workspace not visible

### ISSUE THREAD

**Issue by MarcusE1W** [sbauer322/workspace-nav#8]
Hi
When I use the plugin it works, however you have no visual feedback.
I can't see where the focus is.
The functions work e.g. focus on workspace and then move down a bit, g g to go on top and the o to open a subolder. 
This all seems to work, however there is no visual feedback what is selected.

**Comment by MarcusE1W** [comment]
Hi
Just to make the thing clearer here is a picture:
![lighttable-workspace-nav2](https://cloud.githubusercontent.com/assets/26278354/24549688/6c367496-1612-11e7-8d72-3cd086a623aa.png)

The keys work, but you cannot see on which folder / file the focus is.

**Comment by sbauer322** [comment]
This should be addressed with PR https://github.com/sbauer322/workspace-nav/pull/9 and release 0.0.8.
